<a href="https://colab.research.google.com/github/heysourin/Machine-Learning-Projects/blob/main/Song_recommendation/Song_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/content/songs_recom.csv')

In [4]:
df.shape

(2420, 5)

In [5]:
df.isna().sum()

Song-Name          0
Singer/Artists    10
Genre              0
Album/Movie        3
User-Rating        0
dtype: int64

In [6]:
df = df.dropna()
# or,
# df.dropna(inplace=True)

In [7]:
df.isna().sum()

Song-Name         0
Singer/Artists    0
Genre             0
Album/Movie       0
User-Rating       0
dtype: int64

In [8]:
df.describe()

Song-Name Singer/Artists           Genre      Album/Movie User-Rating
count         2407           2407            2407             2407        2407
unique        2327           1214              20              900          40
top     Tere Naina  Mohammed Rafi  BollywoodDance  Bajirao Mastani      9.4/10
freq             3             55            1220               10         278

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2407 entries, 0 to 2419
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Song-Name       2407 non-null   object
 1   Singer/Artists  2407 non-null   object
 2   Genre           2407 non-null   object
 3   Album/Movie     2407 non-null   object
 4   User-Rating     2407 non-null   object
dtypes: object(5)
memory usage: 112.8+ KB


In [10]:
df.head()

Song-Name                                    Singer/Artists  \
0       Aankh Marey               Kumar Sanu, Mika Singh, Neha Kakkar   
1         Coca Cola                          Neha Kakkar, Tony Kakkar   
2  Apna Time Aayega                                     Ranveer Singh   
3            Mungda             Jyotica Tangri, Shaan, Subhro Ganguly   
4          Tere Bin  Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi   

                    Genre    Album/Movie User-Rating  
0          BollywoodDance         Simmba      8.8/10  
1  BollywoodDanceRomantic    Luka Chuppi      9.0/10  
2          BollywoodDance      Gully Boy      9.7/10  
3          BollywoodDance  Total Dhamaal      9.1/10  
4       BollywoodRomantic         Simmba      9.2/10

In [11]:
df.duplicated().sum()

16

In [12]:
df.drop_duplicates(inplace=True)
# Or,
# df = df.drop_duplicates()

In [13]:
df.duplicated().sum()

0

In [14]:
df.shape

(2391, 5)

In [15]:
df.head()

Song-Name                                    Singer/Artists  \
0       Aankh Marey               Kumar Sanu, Mika Singh, Neha Kakkar   
1         Coca Cola                          Neha Kakkar, Tony Kakkar   
2  Apna Time Aayega                                     Ranveer Singh   
3            Mungda             Jyotica Tangri, Shaan, Subhro Ganguly   
4          Tere Bin  Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi   

                    Genre    Album/Movie User-Rating  
0          BollywoodDance         Simmba      8.8/10  
1  BollywoodDanceRomantic    Luka Chuppi      9.0/10  
2          BollywoodDance      Gully Boy      9.7/10  
3          BollywoodDance  Total Dhamaal      9.1/10  
4       BollywoodRomantic         Simmba      9.2/10

In [16]:
df.tail()

Song-Name                  Singer/Artists  \
2415              Jana Tumhare Pyar Mein                          Mukesh   
2416             Tum Jaise Bigde Babu Se                 Lata Mangeshkar   
2417              O Yaad Nahi Bhool Gaya  Lata Mangeshkar, Suresh Wadkar   
2418   Ladi Re Ladi Tujhse Aankh Jo Ladi                     Jagjit Kaur   
2419  Mummy Aur Daddy Mein Ladai Ho Gayi                     Asha Bhosle   

               Genre                Album/Movie User-Rating  
2415  BollywoodDance                    Sasural      6.2/10  
2416  BollywoodDance  Jab Pyar Kisi Se Hota Hai      7.2/10  
2417  BollywoodDance                      Lamhe      7.5/10  
2418  BollywoodDance          Shola Aur Shabnam      6.5/10  
2419  BollywoodDance          Shola Aur Shabnam      6.6/10

In [17]:
df['User-Rating'].info()

<class 'pandas.core.series.Series'>
Index: 2391 entries, 0 to 2419
Series name: User-Rating
Non-Null Count  Dtype 
--------------  ----- 
2391 non-null   object
dtypes: object(1)
memory usage: 37.4+ KB


In [18]:
def rating(rating):
  rating = str(rating)
  rating = rating.split('/')
  rating = rating[0]
  # return float(rating)
  return rating

rating('9.9/10')

'9.9'

In [19]:
df['User-Rating'] = df['User-Rating'].apply(rating)

In [20]:
df['User-Rating'].info()

<class 'pandas.core.series.Series'>
Index: 2391 entries, 0 to 2419
Series name: User-Rating
Non-Null Count  Dtype 
--------------  ----- 
2391 non-null   object
dtypes: object(1)
memory usage: 37.4+ KB


In [21]:
df['User-Rating']

0       8.8
1       9.0
2       9.7
3       9.1
4       9.2
       ... 
2415    6.2
2416    7.2
2417    7.5
2418    6.5
2419    6.6
Name: User-Rating, Length: 2391, dtype: object

In [22]:
df.head()

Song-Name                                    Singer/Artists  \
0       Aankh Marey               Kumar Sanu, Mika Singh, Neha Kakkar   
1         Coca Cola                          Neha Kakkar, Tony Kakkar   
2  Apna Time Aayega                                     Ranveer Singh   
3            Mungda             Jyotica Tangri, Shaan, Subhro Ganguly   
4          Tere Bin  Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi   

                    Genre    Album/Movie User-Rating  
0          BollywoodDance         Simmba         8.8  
1  BollywoodDanceRomantic    Luka Chuppi         9.0  
2          BollywoodDance      Gully Boy         9.7  
3          BollywoodDance  Total Dhamaal         9.1  
4       BollywoodRomantic         Simmba         9.2

In [23]:
df['Album/Movie'] = df['Album/Movie'].str.replace(' ','')
df['Singer/Artists'] = df['Singer/Artists'].str.replace(',',' ').replace(' ','')

In [24]:
df.head()

Song-Name                                    Singer/Artists  \
0       Aankh Marey               Kumar Sanu  Mika Singh  Neha Kakkar   
1         Coca Cola                          Neha Kakkar  Tony Kakkar   
2  Apna Time Aayega                                     Ranveer Singh   
3            Mungda             Jyotica Tangri  Shaan  Subhro Ganguly   
4          Tere Bin  Asees Kaur  Rahat Fateh Ali Khan  Tanishk Bagchi   

                    Genre   Album/Movie User-Rating  
0          BollywoodDance        Simmba         8.8  
1  BollywoodDanceRomantic    LukaChuppi         9.0  
2          BollywoodDance      GullyBoy         9.7  
3          BollywoodDance  TotalDhamaal         9.1  
4       BollywoodRomantic        Simmba         9.2

In [25]:
df['tags'] = df['Singer/Artists'] + ' ' + df['Genre'] + ' ' + df['Album/Movie'] + ' ' + df['User-Rating']
df['tags'] = df['tags'].apply(lambda x: x.lower())
df['tags'][0]

'kumar sanu  mika singh  neha kakkar bollywooddance simmba 8.8'

In [26]:
new_df = df[['Song-Name', 'tags']]
new_df

Song-Name  \
0                            Aankh Marey   
1                              Coca Cola   
2                       Apna Time Aayega   
3                                 Mungda   
4                               Tere Bin   
...                                  ...   
2415              Jana Tumhare Pyar Mein   
2416             Tum Jaise Bigde Babu Se   
2417              O Yaad Nahi Bhool Gaya   
2418   Ladi Re Ladi Tujhse Aankh Jo Ladi   
2419  Mummy Aur Daddy Mein Ladai Ho Gayi   

                                                   tags  
0     kumar sanu  mika singh  neha kakkar bollywoodd...  
1     neha kakkar  tony kakkar bollywooddanceromanti...  
2             ranveer singh bollywooddance gullyboy 9.7  
3     jyotica tangri  shaan  subhro ganguly bollywoo...  
4     asees kaur  rahat fateh ali khan  tanishk bagc...  
...                                                 ...  
2415                  mukesh bollywooddance sasural 6.2  
2416  lata mangeshkar bollywooddance jabpyarkisiseho...  
2417  lata mangeshkar  suresh wadkar bollywooddance ...  
2418     jagjit kaur bollywooddance sholaaurshabnam 6.5  
2419     asha bhosle bollywooddance sholaaurshabnam 6.6  

[2391 rows x 2 columns]

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [46]:
cv = CountVectorizer(max_features=1900) # max_features --> Features or cols

In [47]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [48]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [54]:
print(vectors[0])

[0 0 0 ... 0 0 0]


In [55]:
vectors.shape

(2391, 1900)

In [56]:
len(cv.vocabulary_)

1900

In [57]:
cv.vocabulary_

{'kumar': 962,
 'sanu': 1507,
 'mika': 1097,
 'singh': 1624,
 'neha': 1192,
 'kakkar': 861,
 'bollywooddance': 318,
 'simmba': 1621,
 'tony': 1773,
 'bollywooddanceromantic': 321,
 'lukachuppi': 1007,
 'ranveer': 1396,
 'gullyboy': 622,
 'jyotica': 842,
 'tangri': 1721,
 'shaan': 1544,
 'subhro': 1668,
 'ganguly': 578,
 'totaldhamaal': 1776,
 'asees': 166,
 'kaur': 898,
 'rahat': 1364,
 'fateh': 553,
 'ali': 90,
 'khan': 909,
 'tanishk': 1722,
 'bagchi': 220,
 'bollywoodromantic': 333,
 'kgf': 905,
 'arun': 163,
 'ikka': 721,
 'romy': 1429,
 'fraudsaiyaan': 560,
 'darshan': 425,
 'raval': 1405,
 'mitron': 1111,
 'rochak': 1423,
 'kohli': 947,
 'ekladkikodekhatohaisalaga': 534,
 'bhasin': 286,
 'vishal': 1833,
 'dadlani': 413,
 'tigerzindahai': 1765,
 'sunanda': 1691,
 'sharma': 1572,
 'guru': 633,
 'randhawa': 1389,
 'cheatindia': 376,
 'dhvani': 472,
 'bhanushali': 282,
 'satyamevajayate': 1525,
 'aastha': 40,
 'gill': 601,
 'badshah': 219,
 'diljit': 483,
 'dosanjh': 514,
 'namasteen

In [58]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [59]:
similarity[0]

array([1.        , 0.375     , 0.35355339, ..., 0.14433757, 0.1767767 ,
       0.1767767 ])

In [60]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])

[(0, 0.9999999999999998),
 (136, 0.5773502691896258),
 (5, 0.5303300858899106),
 (34, 0.5303300858899106),
 (184, 0.5303300858899106),
 (269, 0.5303300858899106),
 (371, 0.5303300858899106),
 (465, 0.5303300858899106),
 (540, 0.5303300858899106),
 (587, 0.5303300858899106),
 (606, 0.5303300858899106),
 (820, 0.5303300858899106),
 (919, 0.5303300858899106),
 (1388, 0.5303300858899106),
 (1600, 0.5303300858899106),
 (1931, 0.5303300858899106),
 (2145, 0.5303300858899106),
 (2272, 0.5303300858899106),
 (2358, 0.5303300858899106),
 (54, 0.4999999999999999),
 (655, 0.4999999999999999),
 (1873, 0.4999999999999999),
 (1823, 0.49029033784546006),
 (363, 0.47434164902525683),
 (716, 0.47434164902525683),
 (2125, 0.4714045207910316),
 (302, 0.4472135954999579),
 (309, 0.4472135954999579),
 (400, 0.4472135954999579),
 (1877, 0.4472135954999579),
 (1966, 0.4472135954999579),
 (181, 0.44194173824159216),
 (11, 0.4330127018922194),
 (19, 0.4330127018922194),
 (35, 0.4330127018922194),
 (40, 0.433012

In [61]:
def recommend(music):
  music_index = new_df[new_df['Song-Name'] == music].index[0] # Excract the index of first matching one
  distances = similarity[music_index]
  music_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

  for i in music_list:
    print(new_df.iloc[i[0]]['Song-Name'])

In [62]:
recommend('Tere Bin')

Sanu Ek Pal Chain
Jag Ghoomeya
Nit Khair Manga
Lag Ja Gale
Nazar Se Nazar Mile


In [63]:
recommend('Hawa Hawa')

Milegi Milegi
Sexy Baliye
Mind Blowing
Aaj Ki Party
The Padman Song


In [64]:
recommend('Mungda')

Kem Cho
Bum Bum Bole
Dastaan-e-Om Shanti Om
Dus Bahane
Main Aisa Kyun Hoon


In [65]:
import pickle
pickle.dump(new_df, open('music_rec.pkl', 'wb'))

In [66]:
pickle.dump(new_df, open('similarities.pkl', 'wb'))

---
## **How sklearn countvectorizer works:**

In [82]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
    'hehe this is',
    'Noice'
]

In [83]:
vectorizer = CountVectorizer()

In [84]:
X = vectorizer.fit_transform(corpus)

In [85]:
print(vectorizer.vocabulary_)

{'this': 10, 'is': 4, 'the': 8, 'first': 2, 'document': 1, 'second': 7, 'and': 0, 'third': 9, 'one': 6, 'hehe': 3, 'noice': 5}


In [86]:
print(X.toarray())

[[0 1 1 0 1 0 0 0 1 0 1]
 [0 2 0 0 1 0 0 1 1 0 1]
 [1 0 0 0 1 0 1 0 1 1 1]
 [0 1 1 0 1 0 0 0 1 0 1]
 [0 0 0 1 1 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0]]


---
## **How cosine algorithm works:**

In [ ]:
def recommend(music):
  music_index = new_df[new_df['Song-Name'] == music].index[0] # Excract the index of first matching one
  distances = similarity[music_index]
  music_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

  for i in music_list:
    print(new_df.iloc[i[0]]['Song-Name'])

In [87]:
music_index = new_df[new_df['Song-Name'] == 'Tere Bin'].index[0]
music_index

4

In [91]:
music_index = new_df[new_df['Song-Name'] == 'Tere Bin'].index[0]
distances = similarity[music_index]
len(distances)

2391

In [100]:
music_index = new_df[new_df['Song-Name'] == 'Tere Bin'].index[0]
distances = similarity[music_index]
music_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6] #shows first 5,
###  enumerate(distances) --> This creates an enumerated list of tuples where each tuple is (index, similarity_score)
music_list # 5 Songs with same cosine similarity

[(84, 0.6454972243679029),
 (227, 0.6454972243679029),
 (234, 0.6454972243679029),
 (355, 0.6454972243679029),
 (495, 0.6454972243679029)]

In [94]:
music_index = new_df[new_df['Song-Name'] == 'Tere Bin'].index[0]
distances = similarity[music_index]
music_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

for i in music_list:
  print(new_df.iloc[i[0]]['Song-Name'])

Sanu Ek Pal Chain
Jag Ghoomeya
Nit Khair Manga
Lag Ja Gale
Nazar Se Nazar Mile
